name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # TODO Gradle cache

      - name: Build with Gradle
        run: ./gradlew build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: master
          extra_plugins: |
              @semantic-release/changelog
              @semantic-release/git
              @semantic-release/gradle
          env:
            GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          dry_run: true
